### PR TITLE
Some optimizations about cn trans

### LINKED ISSUE #8: When the word is marked as known, the cn trans still exists
Screenshot

### PR DESCRIPTION
**Pull request by StanHustler**
- resolved #8 
- let cn trans more readable just like relingo
  Screenshot 2023-10-13 at 20 09 44

### CODE REVIEW

**Comment by sapjax** [comment]
Thanks for the PR, but many times a word has many different meanings, and it is not very accurate to display one alone.

Even if we want to display it like relingo, we can handle the built-in Chinese translation locally, it's better than replacing it in runtime. 

Or we can add a setting option to allow it only to display a single meaning.

**Comment by StanHustler** [comment]
@sapjax 
In fact, this is just a low-invasive change, I did not change the logic on the origin branch.

On the origin branch, each translated text is preceded by a part-of-speech symbol (n\v, etc.), which has very low readability.

| Before | After |
| --- | --- |
| Screenshot 2023-10-14 at 14 02 22 | Screenshot 2023-10-13 at 20 09 44 |

Regarding the issue of polysemy, when you hover the mouse over a word, you will get the same visual effect as the origin branch.

| Normal | Mouse Hover |
| --- | --- |
| Screenshot 2023-10-14 at 13 52 40 | Screenshot 2023-10-14 at 13 52 57 |

And, this is a great repo, thank you for your efforts😃.

**Comment by sapjax** [comment]
> @sapjax In fact, this is just a low-invasive change, I did not change the logic on the origin branch.
> 
> On the origin branch, each translated text is preceded by a part-of-speech symbol (n\v, etc.), which has very low readability.
> 
> Before	After
> Screenshot 2023-10-14 at 14 02 22	Screenshot 2023-10-13 at 20 09 44
> Regarding the issue of polysemy, when you hover the mouse over a word, you will get the same visual effect as the origin branch.
> 
> Normal	Mouse Hover
> Screenshot 2023-10-14 at 13 52 40	Screenshot 2023-10-14 at 13 52 57
> And, this is a great repo, thank you for your efforts😃.

That makes sense, I got it.

**Comment by sapjax** [comment]
@StanHustler  
In the [highlight](https://github.com/sapjax/word-hunter/tree/highlight) branch, I reimplemented the highlight module, Now using [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range) and [Highlight](https://developer.mozilla.org/en-US/docs/Web/API/Highlight) API to mark words, it don't change any DOM structure on page.

This solved a common problem in many pages *(like YouTube)* that using Virtual DOM technology, without modifying DOM, it avoid the disorder of the virtual DOM diff phase, like in https://github.com/sapjax/word-hunter/issues/12 .

The sad news is now we using `Range` to implement highlights, we can't change the text Node anymore, if we add a Chinese translation after a word, the whole text will be broken, and the `Range`s after this translation has wrong offset and works incorrectly. 😢

So in the next major release version, I decided to remove the whole Chinese translation feature totally.

Will add it back when I find a good solution for it.

**Comment by sapjax** [comment]
Nevermind the last comment.
already made translation work in the new highlight version.

**Comment by sapjax** [comment]
already published in [Release 1.1.0](https://github.com/sapjax/word-hunter/releases/tag/1.1.0)

**Pull request merged**
