### PR TITLE
fix: make Highlight use Range instead of AbstractRange

### PR DESCRIPTION
**Pull request by sunnylost**

### CODE REVIEW

**Comment by sapjax** [comment]
What's the problem with the origin code, I don't get it.
It seems that there is no difference 🐶

**Comment by sunnylost** [comment]
In my IDE, the original type override has no effect, Highlight still requires AbstractRange, resulting in numerous error hints that greatly bother me.

**Comment by sapjax** [comment]
> In my IDE, the original type override has no effect, Highlight still requires AbstractRange, resulting in numerous error hints that greatly bother me.

I got it.
This is because we updated the Typescript in https://github.com/sapjax/word-hunter/pull/41, and the new version already added [Highlight/HighlightRegistry](https://github.com/microsoft/TypeScript/pull/57027/files#diff-2d6840937a16179b34b257d0e458eeb5d5ef94043f3888c1679ba3d891aa78b2R137-R142) interfaces.

The problem is caused by the `forEach` function type of `Highlight` interface, we can remove the `HighlightRegistry` declaration, and only override the `Highlight` type:
```typescript
interface Highlight {
  /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Highlight/priority) */
  priority: number
  /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Highlight/type) */
  type: HighlightType
  forEach(callbackfn: (value: Range, key: Range, parent: Highlight) => void, thisArg?: any): void
}

interface Highlight extends Set<Range> {}

declare var Highlight: {
  prototype: Highlight
  new (...initialRanges: Range[]): Highlight
}
```

**Comment by sapjax** [comment]
I think the best way is not to override the `Highlight` type, 
and use `instanceof Range` check before the usage of `Range` specific methods.

**Pull request closed without merging**
